services:
  biomodelos:
    image: biomodelos:2.12.5
    build:
      context: .
    container_name: biomodelos_website
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
     - "${METHODS_FOLDER}:/var/www/BioModelos/public/methods"
     - "${MODELS_FOLDER}:/var/www/BioModelos/public/models"
     - "${THUMBS_FOLDER}:/var/www/BioModelos/public/thumbs"
     - "${ZIPS_FOLDER}:/var/www/BioModelos/public/zip"
     - "${UPLOADS_FOLDER}:/var/www/BioModelos/public/uploads"
     - "${CREDENTIALS_FILE}:/var/www/BioModelos/config/credentials/development.yml.enc"
     
    ports:
     - "${HOST_PORT}:3000"
    command: bundle exec rails server -b 0.0.0.0
    restart: always
    